using System.Collections.Generic;
using System.Globalization;

namespace Amfetamin
{
    /// <summary>UI text. Turkish on Turkish Windows, English elsewhere.</summary>
    internal static class S
    {
        public static readonly bool Turkish =
            CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "tr" ||
            CultureInfo.CurrentCulture.TwoLetterISOLanguageName == "tr";

        public static string T(string key, params object[] args)
        {
            var table = Turkish ? Tr : En;
            if (!table.TryGetValue(key, out var text) && !En.TryGetValue(key, out text)) text = key;
            return args.Length == 0 ? text : string.Format(text, args);
        }

        private static readonly Dictionary<string, string> Tr = new Dictionary<string, string>
        {
            ["app_tagline"] = "DPI bypass · Discord · anti-cheat uyumlu",
            ["nav_home"] = "Ana sayfa",
            ["nav_games"] = "Oyunlar",
            ["nav_settings"] = "Ayarlar",
            ["nav_logs"] = "Kayıtlar",
            ["nav_help"] = "Teşhis",

            ["state_connected"] = "Bağlı",
            ["state_disconnected"] = "Bağlı değil",
            ["state_starting"] = "Bağlanıyor…",
            ["state_stopping"] = "Durduruluyor…",
            ["state_setup"] = "Kurulum gerekli",
            ["state_hint_connected"] = "Engelli siteler ve Discord açık. Oyun trafiği doğrudan gidiyor.",
            ["state_hint_disconnected"] = "Bağlanmak için butona bas.",
            ["state_hint_setup"] = "İlk kullanımda Npcap ve motor kurulacak. Birkaç dakika sürebilir.",
            ["btn_connect"] = "BAĞLAN",
            ["btn_disconnect"] = "BAĞLANTIYI KES",
            ["btn_setup"] = "KUR VE BAĞLAN",
            ["btn_cancel"] = "İptal",

            ["card_engine"] = "Motor",
            ["card_npcap"] = "Npcap",
            ["card_autostart"] = "Otomatik başlatma",
            ["card_discord"] = "Discord",
            ["val_running"] = "Çalışıyor",
            ["val_stopped"] = "Kapalı",
            ["val_installed"] = "Kurulu",
            ["val_missing"] = "Eksik",
            ["val_on"] = "Açık",
            ["val_off"] = "Kapalı",
            ["val_ok"] = "Erişilebilir",
            ["val_fail"] = "Erişilemiyor",
            ["val_checking"] = "Kontrol…",
            ["val_unknown"] = "—",

            ["quick_test"] = "Bağlantı testi",
            ["quick_retune"] = "TTL'i yeniden ayarla",
            ["quick_npcap"] = "Npcap'i kur / onar",
            ["quick_cleanup"] = "Ağ ayarlarını onar",

            ["warn_conflict"] = "Çakışan program çalışıyor: {0}. Bağlantı sorunlarına yol açabilir.",
            ["warn_conflict_close"] = "Kapat",

            ["games_title"] = "Oyun modu",
            ["games_desc"] = "Seçilen oyunların trafiği tünele girmez, doğrudan internete gider. Ping etkilenmez; anti-cheat (EAC, Vanguard) sorun çıkarmaz.",
            ["games_auto"] = "Tüm oyunlar (otomatik)",
            ["games_auto_desc"] = "Web ve Discord dışındaki tüm UDP trafiğini doğrudan gönderir. Ping sorunu yaşıyorsan bunu aç. Oyun sunucusuna ilk bağlanışta 1–2 saniyelik bir yeniden deneme olabilir.",
            ["games_presets"] = "Oyun profilleri",
            ["games_custom"] = "Özel portlar",
            ["games_custom_desc"] = "Satır başına bir kural: udp:3074, tcp:27015, udp:5000-5500, 3478",
            ["games_invalid"] = "Geçersiz kural: {0}",
            ["btn_save"] = "Kaydet",
            ["saved"] = "Kaydedildi.",
            ["saved_restarted"] = "Kaydedildi — motor yeni ayarlarla yeniden başlatıldı.",

            ["set_general"] = "Genel",
            ["set_autostart"] = "Windows açılışında otomatik bağlan",
            ["set_tray"] = "Kapatınca simge durumuna küçült (arka planda çalışsın)",
            ["set_reconnect"] = "Motor kapanırsa otomatik yeniden bağlan",
            ["set_zerotier"] = "Bağlanırken ZeroTier'i kapat",
            ["set_network"] = "Ağ",
            ["set_dns"] = "Şifreli DNS sunucusu",
            ["set_ttl"] = "Sahte paket TTL değeri",
            ["set_ttl_desc"] = "Otomatik ayar çoğu zaman en iyisidir. Sayfalar açılmıyorsa TTL'i yeniden ayarla.",
            ["set_autotune"] = "İlk bağlantıda TTL'i otomatik ayarla",
            ["set_ipv4"] = "IPv6'yı devre dışı bırak (önerilir — IPv6 trafiği tünele girmez)",
            ["set_lan"] = "Yerel ağı (LAN) tünelden hariç tut",
            ["set_verbose"] = "Ayrıntılı motor kaydı (sorun giderme)",
            ["dns_auto"] = "Otomatik (Cloudflare + Google)",

            ["logs_engine"] = "Motor",
            ["logs_app"] = "Uygulama",
            ["logs_follow"] = "Canlı izle",
            ["logs_open"] = "Klasörü aç",
            ["logs_export"] = "ZIP olarak dışa aktar",
            ["logs_exported"] = "Kaydedildi: {0}",

            ["help_diag"] = "Teşhis raporu",
            ["help_diag_desc"] = "Sorun bildirirken bu raporu ekle. Kişisel veri içermez; ağ bağdaştırıcıları, DNS ve bağlantı testleri yer alır.",
            ["help_run"] = "Raporu oluştur",
            ["help_save"] = "Dosyaya kaydet",
            ["help_about"] = "Hakkında",
            ["help_update"] = "Güncellemeleri denetle",
            ["help_uninstall"] = "Cihazdan kaldır",
            ["help_github"] = "GitHub sayfası",
            ["update_none"] = "En güncel sürümü kullanıyorsun ({0}).",
            ["update_available"] = "Yeni sürüm var: {0}. İndirme sayfası açılsın mı?",
            ["update_failed"] = "Güncelleme denetlenemedi: {0}",

            ["busy"] = "İşlem sürüyor…",
            ["step_prepare"] = "Hazırlanıyor…",
            ["step_npcap_download"] = "Npcap indiriliyor…",
            ["step_npcap_install"] = "Npcap kurulum penceresi açıldı. Kurulumu tamamla (Kabul et → Kur → Bitti).",
            ["step_npcap_done"] = "Npcap kuruldu.",
            ["step_engine_download"] = "Motor indiriliyor… %{0}",
            ["step_engine_copy"] = "Motor kuruluyor…",
            ["step_engine_start"] = "Motor başlatılıyor…",
            ["step_autostart"] = "Otomatik başlatma ayarlanıyor…",
            ["step_ttl_try"] = "TTL {0} deneniyor ({1}/{2})…",
            ["step_ttl_ok"] = "TTL {0} çalışıyor.",
            ["step_ttl_none"] = "Hiçbir TTL ile {0} açılamadı; {1} kullanılıyor. İnternet bağlantını ve çakışan programları kontrol et.",
            ["step_test"] = "Bağlantı test ediliyor…",
            ["step_cleanup"] = "Ağ ayarları onarılıyor…",

            ["done_connected"] = "Bağlandı.",
            ["done_disconnected"] = "Bağlantı kesildi.",
            ["done_setup"] = "Kurulum tamamlandı, bağlısın.",
            ["done_cleanup"] = "Ağ ayarları onarıldı (DNS ve rotalar geri alındı).",
            ["done_npcap_present"] = "Npcap zaten kurulu.",

            ["test_result"] = "{0}: {1}",
            ["test_ok"] = "OK ({0} ms)",
            ["test_fail"] = "başarısız ({0})",

            ["err_title"] = "amfetamin",
            ["err_npcap_missing"] = "Npcap kurulu değil. Önce Npcap kurulmalı.",
            ["err_npcap_cancelled"] = "Npcap kurulumu tamamlanmadı. Tekrar denemek için \"Npcap'i kur / onar\"a bas.",
            ["err_npcap_signature"] = "İndirilen Npcap kurulum dosyası doğrulanamadı.",
            ["err_engine_missing"] = "Motor dosyası bulunamadı ve indirilemedi: {0}",
            ["err_checksum"] = "Motor dosyası doğrulanamadı (SHA256 uyuşmuyor).",
            ["err_engine_start"] = "Motor başlatılamadı:\n{0}",
            ["err_engine_exited"] = "Motor beklenmedik şekilde kapandı. Son kayıtlar:\n{0}",
            ["err_admin"] = "amfetamin yönetici olarak çalışmalı.",
            ["err_download"] = "İndirme başarısız: {0}",

            ["confirm_uninstall"] = "amfetamin bu bilgisayardan kaldırılsın mı?\n\nMotor durdurulur, ağ ayarları geri alınır ve otomatik başlatma kaldırılır. Npcap'i ayrıca Uygulamalar'dan kaldırabilirsin.",
            ["uninstalled"] = "amfetamin kaldırıldı. Bu pencere kapanacak.",
            ["confirm_exit_running"] = "Bağlantı açık. Çıkarken bağlantı kesilsin mi?\n\nEvet: kes ve çık · Hayır: arka planda çalışmaya devam etsin",

            ["tray_open"] = "Aç",
            ["tray_connect"] = "Bağlan",
            ["tray_disconnect"] = "Bağlantıyı kes",
            ["tray_exit"] = "Çıkış",
            ["tray_hidden"] = "amfetamin arka planda çalışıyor.",
            ["tray_engine_crashed"] = "Motor kapandı, yeniden bağlanılıyor…",
            ["tray_engine_failed"] = "Motor tekrar tekrar kapandı. Ayrıntılar için uygulamayı aç.",
            ["already_running"] = "amfetamin zaten açık.",
            ["migrate_running"] = "Önceki sürüm güncelleniyor (ayarların korunuyor)…",
            ["migrate_done"] = "Yeni sürüme geçildi. Ayarların korundu.",
            ["update_downloading"] = "Güncelleme indiriliyor… %{0}",
            ["update_installing"] = "{0} kuruluyor, birkaç saniye içinde yeniden açılacak…",
            ["update_available_short"] = "Yeni sürüm var: {0}. Teşhis → Güncellemeleri denetle.",
            ["set_autoupdate"] = "Güncellemeleri otomatik kur",
        };

        private static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            ["app_tagline"] = "DPI bypass · Discord · anti-cheat friendly",
            ["nav_home"] = "Home",
            ["nav_games"] = "Games",
            ["nav_settings"] = "Settings",
            ["nav_logs"] = "Logs",
            ["nav_help"] = "Diagnostics",

            ["state_connected"] = "Connected",
            ["state_disconnected"] = "Not connected",
            ["state_starting"] = "Connecting…",
            ["state_stopping"] = "Stopping…",
            ["state_setup"] = "Setup required",
            ["state_hint_connected"] = "Blocked sites and Discord are reachable. Game traffic goes direct.",
            ["state_hint_disconnected"] = "Press the button to connect.",
            ["state_hint_setup"] = "Npcap and the engine will be installed on first use. This can take a few minutes.",
            ["btn_connect"] = "CONNECT",
            ["btn_disconnect"] = "DISCONNECT",
            ["btn_setup"] = "INSTALL & CONNECT",
            ["btn_cancel"] = "Cancel",

            ["card_engine"] = "Engine",
            ["card_npcap"] = "Npcap",
            ["card_autostart"] = "Auto-start",
            ["card_discord"] = "Discord",
            ["val_running"] = "Running",
            ["val_stopped"] = "Stopped",
            ["val_installed"] = "Installed",
            ["val_missing"] = "Missing",
            ["val_on"] = "On",
            ["val_off"] = "Off",
            ["val_ok"] = "Reachable",
            ["val_fail"] = "Unreachable",
            ["val_checking"] = "Checking…",
            ["val_unknown"] = "—",

            ["quick_test"] = "Connection test",
            ["quick_retune"] = "Re-tune TTL",
            ["quick_npcap"] = "Install / repair Npcap",
            ["quick_cleanup"] = "Repair network settings",

            ["warn_conflict"] = "A conflicting program is running: {0}. It may cause connection problems.",
            ["warn_conflict_close"] = "Close it",

            ["games_title"] = "Game mode",
            ["games_desc"] = "Traffic of the selected games skips the tunnel and goes straight to the internet. No ping impact, no anti-cheat (EAC, Vanguard) issues.",
            ["games_auto"] = "All games (automatic)",
            ["games_auto_desc"] = "Sends all UDP traffic except web and Discord directly. Turn this on if you have ping problems. The first connection to a game server may retry once (1–2 s).",
            ["games_presets"] = "Game profiles",
            ["games_custom"] = "Custom ports",
            ["games_custom_desc"] = "One rule per line: udp:3074, tcp:27015, udp:5000-5500, 3478",
            ["games_invalid"] = "Invalid rule: {0}",
            ["btn_save"] = "Save",
            ["saved"] = "Saved.",
            ["saved_restarted"] = "Saved — engine restarted with the new settings.",

            ["set_general"] = "General",
            ["set_autostart"] = "Connect automatically when Windows starts",
            ["set_tray"] = "Minimize to tray when closed (keep running)",
            ["set_reconnect"] = "Reconnect automatically if the engine stops",
            ["set_zerotier"] = "Close ZeroTier when connecting",
            ["set_network"] = "Network",
            ["set_dns"] = "Encrypted DNS server",
            ["set_ttl"] = "Fake packet TTL",
            ["set_ttl_desc"] = "Automatic tuning is usually best. Re-tune TTL if pages don't load.",
            ["set_autotune"] = "Tune TTL automatically on first connect",
            ["set_ipv4"] = "Disable IPv6 answers (recommended — IPv6 traffic bypasses the tunnel)",
            ["set_lan"] = "Keep local network (LAN) out of the tunnel",
            ["set_verbose"] = "Verbose engine log (troubleshooting)",
            ["dns_auto"] = "Automatic (Cloudflare + Google)",

            ["logs_engine"] = "Engine",
            ["logs_app"] = "App",
            ["logs_follow"] = "Follow",
            ["logs_open"] = "Open folder",
            ["logs_export"] = "Export as ZIP",
            ["logs_exported"] = "Saved: {0}",

            ["help_diag"] = "Diagnostic report",
            ["help_diag_desc"] = "Attach this report when reporting a problem. It contains network adapters, DNS and connectivity tests — no personal data.",
            ["help_run"] = "Create report",
            ["help_save"] = "Save to file",
            ["help_about"] = "About",
            ["help_update"] = "Check for updates",
            ["help_uninstall"] = "Uninstall",
            ["help_github"] = "GitHub page",
            ["update_none"] = "You are on the latest version ({0}).",
            ["update_available"] = "A new version is available: {0}. Open the download page?",
            ["update_failed"] = "Could not check for updates: {0}",

            ["busy"] = "Working…",
            ["step_prepare"] = "Preparing…",
            ["step_npcap_download"] = "Downloading Npcap…",
            ["step_npcap_install"] = "The Npcap installer is open. Finish it (I Agree → Install → Finish).",
            ["step_npcap_done"] = "Npcap installed.",
            ["step_engine_download"] = "Downloading engine… {0}%",
            ["step_engine_copy"] = "Installing engine…",
            ["step_engine_start"] = "Starting engine…",
            ["step_autostart"] = "Setting up auto-start…",
            ["step_ttl_try"] = "Trying TTL {0} ({1}/{2})…",
            ["step_ttl_ok"] = "TTL {0} works.",
            ["step_ttl_none"] = "{0} did not open with any TTL; using {1}. Check your internet connection and conflicting programs.",
            ["step_test"] = "Testing connection…",
            ["step_cleanup"] = "Repairing network settings…",

            ["done_connected"] = "Connected.",
            ["done_disconnected"] = "Disconnected.",
            ["done_setup"] = "Setup complete, you are connected.",
            ["done_cleanup"] = "Network settings repaired (DNS and routes restored).",
            ["done_npcap_present"] = "Npcap is already installed.",

            ["test_result"] = "{0}: {1}",
            ["test_ok"] = "OK ({0} ms)",
            ["test_fail"] = "failed ({0})",

            ["err_title"] = "amfetamin",
            ["err_npcap_missing"] = "Npcap is not installed. Install Npcap first.",
            ["err_npcap_cancelled"] = "Npcap setup did not complete. Press \"Install / repair Npcap\" to try again.",
            ["err_npcap_signature"] = "The downloaded Npcap installer could not be verified.",
            ["err_engine_missing"] = "Engine file not found and could not be downloaded: {0}",
            ["err_checksum"] = "Engine file could not be verified (SHA256 mismatch).",
            ["err_engine_start"] = "The engine could not start:\n{0}",
            ["err_engine_exited"] = "The engine stopped unexpectedly. Last log lines:\n{0}",
            ["err_admin"] = "amfetamin must run as administrator.",
            ["err_download"] = "Download failed: {0}",

            ["confirm_uninstall"] = "Remove amfetamin from this computer?\n\nThe engine is stopped, network settings are restored and auto-start is removed. You can remove Npcap separately from Apps.",
            ["uninstalled"] = "amfetamin was removed. This window will close.",
            ["confirm_exit_running"] = "You are connected. Disconnect on exit?\n\nYes: disconnect and exit · No: keep running in the background",

            ["tray_open"] = "Open",
            ["tray_connect"] = "Connect",
            ["tray_disconnect"] = "Disconnect",
            ["tray_exit"] = "Exit",
            ["tray_hidden"] = "amfetamin keeps running in the background.",
            ["tray_engine_crashed"] = "The engine stopped, reconnecting…",
            ["tray_engine_failed"] = "The engine keeps stopping. Open the app for details.",
            ["already_running"] = "amfetamin is already open.",
            ["migrate_running"] = "Upgrading the previous version (your settings are kept)…",
            ["migrate_done"] = "Upgraded to the new version. Your settings were kept.",
            ["update_downloading"] = "Downloading update… {0}%",
            ["update_installing"] = "Installing {0}, the app will reopen in a few seconds…",
            ["update_available_short"] = "New version available: {0}. Diagnostics → Check for updates.",
            ["set_autoupdate"] = "Install updates automatically",
        };
    }
}
